version = 2
extends = "real-home"
prompt = ".cap/prompts/work.md"

[skills]
add = ["openspec-explore", "openspec-propose", "openspec-update-change", "openspec-apply-change", "openspec-sync-specs", "openspec-archive-change"]
mask = []
replace = []

[mcps]
add = []
mask = []
replace = []

[hooks]
add = []
mask = []
replace = []

[plugins]
add = []
mask = []
replace = []
